# Author: Erik Martin-Dorel, 2020

stages:
  - lint
  - test

.python:
  image: python:3-alpine
  before_script:
    - python --version

lint-python:
  stage: lint
  extends: .python
  script:
    - pip install --no-cache-dir -r requirements_lint.txt
    - flake8 *.py

lint-script:
  stage: lint
  image:
    name: koalaman/shellcheck-alpine:stable
    entrypoint: ["/bin/ash", "-c"]
  script:
    - shellcheck --color=always *.sh

test-python:
  stage: test
  extends: .python
  script:
    - pip install --no-cache-dir -r requirements.txt
    - ./keeper.py --version
    - pytest *.py
